---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_connection: docker

vector:
  hosts:
    vector-01:
      ansible_connection: docker

local:
  hosts:
    localhost:
      ansible_connection: local